name: release
on:
  push:
    branches: [main]
  release:
    types:
    - created
jobs:
  code:
    uses: cyberuni/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'
      node-version: '[24]'

  release:
    runs-on: ubuntu-latest
    needs: code
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
    - name: "Start X Virtual Frame Buffer"
      run: "echo \"DISPLAY=:99.0\" >> $GITHUB_ENV && Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &"

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.CI_GITHUB_TOKEN }}
    - uses: pnpm/action-setup@v3
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm
    - run: pnpm install
    - run: pnpm add -g ovsx
    - name: Publish
      # if: success() && startsWith(github.ref, 'refs/tags/')
      run: pnpx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
  # docgen:
  #     uses: unional/.github/.github/workflows/pnpm-docs.yml@main
  #     needs: release
